<%@ Page Title="Manage news" Language="C#" MasterPageFile="~/Site.master" AutoEventWireup="true" CodeBehind="NewsAdmin.aspx.cs" Inherits="Project_Shode.NewsAdmin" %>

<asp:Content runat="server" ID="BodyContent" ContentPlaceHolderID="MainContent">
    <section id="location">
        <asp:HyperLink ID="HyperLink1" runat="server" NavigateUrl="~/Default.aspx">Shode</asp:HyperLink> > 
        <asp:HyperLink ID="HyperLink2" runat="server" NavigateUrl="~/Contact.aspx">Contact</asp:HyperLink>
    </section>

   <hgroup> <h2>Manage your news items</h2><hgroup>
   <asp:GridView ID="GridView1" runat="server" 
            AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" 
            AutoGenerateDeleteButton="True" 
            DataKeyNames="code" DataSourceID="SqlDataSource1" 
        EnableModelValidation="True" BackColor="White" BorderColor="#CCCCCC" 
        BorderStyle="None" BorderWidth="1px" CellPadding="4" ForeColor="Black" 
        GridLines="Horizontal">
        <Columns>
            <asp:TemplateField>
                <ItemTemplate>
                    <asp:HyperLink ID="HyperLink1" runat="server" Text="Edit" NavigateUrl='<%#Eval("code","NewsEdit.aspx?code={0}")%>'  />
                </ItemTemplate>
            </asp:TemplateField>
            <asp:BoundField DataField="title" HeaderText="Title" SortExpression="title" />
            <asp:BoundField DataField="public_date" HeaderText="public_date" 
                SortExpression="public_date" />
            <asp:BoundField DataField="creator" HeaderText="Author" 
                SortExpression="creator" />
            <asp:BoundField DataField="code" HeaderText="Code" ReadOnly="True" 
                SortExpression="code" />
        </Columns>
        <FooterStyle BackColor="#CCCC99" ForeColor="Black" />
        <HeaderStyle BackColor="#333333" Font-Bold="True" ForeColor="White" />
        <PagerStyle BackColor="White" ForeColor="Black" HorizontalAlign="Right" />
        <SelectedRowStyle BackColor="#CC3333" Font-Bold="True" ForeColor="White" />
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" 
            ConnectionString="<%$ ConnectionStrings:ShodeDDBB %>" 
            DeleteCommand="DELETE FROM [news] WHERE [code] = @code" 
            InsertCommand="INSERT INTO [news] ([title], [public_date], [creator], [code]) VALUES (@title, @public_date, @creator, @code)" 
            SelectCommand="SELECT [title], [public_date], [creator], [code] FROM [news]" 
            UpdateCommand="UPDATE [news] SET [title] = @title, [public_date] = @public_date, [creator] = @creator WHERE [code] = @code">
            <DeleteParameters>
                <asp:Parameter Name="code" Type="Int32" />
            </DeleteParameters>
            <InsertParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="public_date" Type="String" />
                <asp:Parameter Name="creator" Type="String" />
                <asp:Parameter Name="code" Type="Int32" />
            </InsertParameters>
            <UpdateParameters>
                <asp:Parameter Name="title" Type="String" />
                <asp:Parameter Name="public_date" Type="String" />
                <asp:Parameter Name="creator" Type="String" />
                <asp:Parameter Name="code" Type="Int32" />
            </UpdateParameters>
        </asp:SqlDataSource>
    </asp:Content>
